variable "basename" {}
variable "endpoint" {}
variable "tags" {}
variable "resource_group_id" {}
variable "iaas_endpoint" {}
variable "iaas_endpoint_version" {}
variable "subnet_id" {}
variable "instance_ids" {}
variable "vpc_security_group_id" {}
variable "vpc_id" {}